version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "7180:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "7100:80"
    depends_on:
      - backend
    networks:
      - app-network
  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - "7200:80"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge